name: geospatial
channels:
  - defaults
  - conda-forge
dependencies:
  - geopandas=0.12.2=py39haa95532_0
  - pandas=2.1.0=py39h32e6231_0
  - streamlit-folium=0.18.0=pyhd8ed1ab_0
  - pip:
      - streamlit==1.29.0
